### ISSUE TITLE
TypeError: vConsolePlugin is not a function

### ISSUE THREAD

**Issue by xiaweiss** [venojs/vite-plugin-simple-vconsole#1]
<img width="965" alt="image" src="https://user-images.githubusercontent.com/17960084/183553328-5b946610-3703-49f6-8d1e-45910c6363b2.png">

package.json info: 
"type": "module",
"vite": "^3.0.4",

**Comment by burnoutprojects** [comment]
@xiaweiss a little hack to start working with this plugin is to replace the `import vConsolePlugin from 'vite-plugin-simple-vconsole'` with `import vConsolePlugin from 'vite-plugin-simple-vconsole/dist/index.mjs'`

**Comment by xiaweiss** [comment]
thank you. it works

**Comment by heflyaway** [comment]
@burnoutprojects thanks for your answer！
@xiaweiss it support conditional exports after 0.1.11, you can use `import vConsolePlugin from 'vite-plugin-simple-vconsole'` directly

**Comment by xiaweiss** [comment]
ok, thank you
